services:
    mongo:
        image: mongo
        container_name: hubxp_mongodb
        hostname: hubxp_mongodb
        command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
        ports:
            - 27017:27017
        networks:
            - hubxp-network
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
            interval: 10s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        volumes:
            - 'mongo1_data:/data/db'
            - 'mongo1_config:/data/configdb'

    localstack:
        image: localstack/localstack
        container_name: hubxp_localstack
        ports:
            - '4566:4566'
            - '4572:4572'
        environment:
            - SERVICES=s3
            - DEBUG=1
            - AWS_DEFAULT_REGION=us-east-1
        volumes:
            - './infra/localstack-data:/var/lib/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'

    server:
        build:
            context: ./apps/server
            dockerfile: Dockerfile
        container_name: hubxp_server
        environment:
            - MONGODB_URL=mongodb://hubxp_mongodb:27017/hubxp_demo?directConnection=true&replicaSet=rs0
            - AWS_ENDPOINT=http://localstack:4566
            - LOCALSTACK_PORT=${LOCALSTACK_PORT}
            - APP_PORT=${APP_PORT}
        depends_on:
            mongo:
                condition: service_healthy
            localstack:
                condition: service_started
        ports:
            - '${APP_PORT}:${APP_PORT}'
        networks:
            - hubxp-network
        volumes:
            - ./apps/server:/app
            - /app/node_modules
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:${APP_PORT}/health']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    web:
        build:
            context: ./apps/web
            dockerfile: Dockerfile
        container_name: hubxp_web
        environment:
            - REACT_APP_API_URL=http://localhost:3003
        ports:
            - '3000:3000'
        networks:
            - hubxp-network
        volumes:
            - ./apps/web:/app
            - /app/node_modules
        depends_on:
            server:
                condition: service_healthy
        stdin_open: true
        tty: true

networks:
    hubxp-network:
        driver: bridge

volumes:
    mongo1_data:
    mongo1_config:
