service: sales-report-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 10

plugins:
  - serverless-offline

functions:
  processSalesReport:
    handler: ./dist/serverless/reports.salesReport
    events:
      - http:
          path: reports/sales
          method: get
  sendNotification:
    handler: ./dist/serverless/notification.sendNotification
    events:
      - http:
          path: notifications/send
          method: post

custom:
  serverless-offline:
    httpPort: 3004