version: '3.8'
services:
  mongo:
    image: mongo
    container_name: hubxp_mongodb
    hostname: hubxp_mongodb
    command: ['--replSet', 'rs0', '--bind_ip_all']
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "rs.status()"]
      interval: 10s
      start_period: 30s
      retries: 3
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  mongo-data:
